version = 0.1

[default.deploy.parameters]
stack_name = "karaoke-enhanced-stack"
resolve_s3 = true
s3_prefix = "karaoke-enhanced-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Region=\"us-east-1\""