version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "music-box-game"
s3_prefix = "music-box-game"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\""